[package]
name        = "dotify"
version     = "1.0.0"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
description = "Convert bytes to braille and back again"
license     = "CC0-1.0"
homepage    = "https://github.com/casey/dotify"

[dependencies]
clap = "2.31.2"
